(function(){
'use strict';
const KEYS={math:'cuoti_v3',words:'dudu_vocab_v2',history:'dudu_vocab_history_v2',daily:'dudu_vocab_daily_v1',settings:'dudu_vocab_settings_v1',profile:'dudu_user_profile_v1',mathActivity:'dudu_math_activity_v1',activity:'dudu_activity_log_v1',backup:'dudu_last_backup_at_v1'};
const DAY=86400000;
const safe=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const dateKey=t=>{const d=new Date(t||Date.now()),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const epochDay=t=>Math.floor((t||Date.now())/DAY);
const escapeHtml=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function notify(text){if(typeof window.toast==='function')window.toast(text);else alert(text)}
function download(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),800)}
function logActivity(type,text,count=1,meta={}){const list=safe(KEYS.activity,[]);list.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2),type,text,count,at:Date.now(),...meta});write(KEYS.activity,list.slice(-1200));}
function migrateMath(){const list=safe(KEYS.math,[]);if(!Array.isArray(list))return;let changed=false;list.forEach(q=>{if('ansImg'in q){delete q.ansImg;changed=true}if(!q.lastReviewedAt&&q.edited)q.lastReviewedAt=q.edited});if(changed)write(KEYS.math,list)}
function repairEnglishDaily(){const words=safe(KEYS.words,[]),daily=safe(KEYS.daily,{});if(!Array.isArray(words)||!daily||typeof daily!=='object')return;const counts={};words.forEach(w=>{if(w.introducedDay!=null)counts[String(w.introducedDay)]=(counts[String(w.introducedDay)]||0)+1});Object.entries(counts).forEach(([k,n])=>{daily[k]={activities:0,correct:0,sessions:0,...(daily[k]||{}),newWords:n}});Object.keys(daily).forEach(k=>{if(!(k in counts)&&daily[k]?.newWords)daily[k].newWords=0});write(KEYS.daily,daily)}
window.exportAllDuduData=function(){const payload={app:'dudu-cuotuiben',version:2,type:'complete',exportedAt:new Date().toISOString(),data:{}};Object.entries(KEYS).forEach(([name,key])=>{if(name!=='backup')payload.data[key]=safe(key,null)});download(payload,`dudu-complete-backup-${new Date().toISOString().slice(0,10)}.json`);localStorage.setItem(KEYS.backup,new Date().toISOString());updateBackupText();notify('完整备份已导出')};
window.importAllDuduData=async function(input){const file=input?.files?.[0];if(!file)return;try{const payload=JSON.parse(await file.text());if(payload?.type!=='complete'||!payload.data)throw new Error('不是嘟嘟错题本完整备份');if(!confirm('恢复完整备份会覆盖当前数学、英语、资料和学习记录，确定继续吗？'))return;Object.entries(payload.data).forEach(([key,val])=>{if(Object.values(KEYS).includes(key)&&key!==KEYS.backup){if(val===null)localStorage.removeItem(key);else write(key,val)}});localStorage.setItem(KEYS.backup,new Date().toISOString());location.reload()}catch(e){notify(e.message||'完整备份导入失败')}finally{input.value=''}};
function updateBackupText(){const el=document.getElementById('lastBackupText'),v=localStorage.getItem(KEYS.backup);if(el)el.textContent=v?`上次完整备份：${new Date(v).toLocaleString('zh-CN')}`:'尚未进行完整备份'}
function injectBackupManager(){const modal=document.querySelector('.profile-body');if(!modal||modal.querySelector('.complete-backup'))return;const box=document.createElement('section');box.className='complete-backup';box.innerHTML=`<div><b>完整数据备份</b><span id="lastBackupText"></span></div><div class="backup-actions"><button type="button" onclick="exportAllDuduData()">导出全部数据</button><label>恢复全部数据<input type="file" accept=".json,application/json" onchange="importAllDuduData(this)"></label></div><p>包含数学错题、英语单词、学习记录、昵称、年级和目标设置。</p>`;modal.insertBefore(box,modal.querySelector('.profile-save'));updateBackupText()}
function snackbar(message,undo){let bar=document.getElementById('undoBar');if(!bar){bar=document.createElement('div');bar.id='undoBar';bar.className='undo-bar';document.body.appendChild(bar)}bar.innerHTML=`<span>${escapeHtml(message)}</span><button type="button">撤销</button>`;bar.classList.add('show');const btn=bar.querySelector('button');btn.onclick=()=>{undo();bar.classList.remove('show')};clearTimeout(bar._t);bar._t=setTimeout(()=>bar.classList.remove('show'),10000)}
function wrapDelete(name,key,label){const fn=window[name];if(typeof fn!=='function'||fn.__undo)return;const wrapped=function(...args){const before=localStorage.getItem(key);const oldConfirm=window.confirm;let confirmed=false;window.confirm=(msg)=>{const r=oldConfirm(msg);confirmed=confirmed||r;return r};try{const result=fn.apply(this,args);setTimeout(()=>{if(confirmed&&before!==localStorage.getItem(key))snackbar(`${label}已删除`,()=>{if(before==null)localStorage.removeItem(key);else localStorage.setItem(key,before);location.reload()})},0);return result}finally{window.confirm=oldConfirm}};wrapped.__undo=true;window[name]=wrapped}
function wrapActivity(name,type,text){const fn=window[name];if(typeof fn!=='function'||fn.__activity)return;const wrapped=function(...args){const before=localStorage.getItem(KEYS.math);const result=fn.apply(this,args);setTimeout(()=>{if(before!==localStorage.getItem(KEYS.math))logActivity(type,text)},0);return result};wrapped.__activity=true;window[name]=wrapped}
function overrideMathCard(){if(typeof window.cardHtml!=='function')return;window.cardHtml=function(x){const checked=(typeof selected!=='undefined'&&selected.has)?selected.has(x.id):false;const date=new Date(x.at||Date.now()).toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'});const review=x.lastReviewedAt?new Date(x.lastReviewedAt).toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'}):'—';return `<article class="q-card ${checked?'selected':''}" data-id="${x.id}"><div class="q-head"><label class="q-check-wrap" title="选择这道题"><input type="checkbox" ${checked?'checked':''} onchange="toggleSelection('${x.id}',this.checked)"><span></span></label>${x.tag?`<span class="q-sub">${escapeHtml(x.tag)}</span>`:'<span class="q-sub muted-pill">未分类</span>'}<span class="q-status ${x.status||'wrong'}">${({wrong:'未掌握',review:'复习中',done:'已掌握'})[x.status]||'未掌握'}</span></div><div class="q-text">${escapeHtml(x.q)}</div>${x.a?`<div class="q-answer-preview"><b>答案：</b>${escapeHtml(x.a).slice(0,80)}${x.a.length>80?'…':''}</div>`:''}<div class="q-meta"><span>${x.reason?`出错原因：${escapeHtml(x.reason)}`:'手动录入'}</span><span>录入 ${date} · 最近复习 ${review}</span></div><div class="q-actions"><button onclick="openEdit('${x.id}')">编辑</button><button onclick="removeQuestion('${x.id}')">删除</button></div></article>`}
}
function formulaToolbar(){const q=document.getElementById('fQ');if(!q||document.getElementById('formulaToolbar'))return;const bar=document.createElement('div');bar.id='formulaToolbar';bar.className='formula-toolbar';['×','÷','±','²','³','√','π','≤','≥','≠','（','）','／'].forEach(s=>{const b=document.createElement('button');b.type='button';b.textContent=s;b.onclick=()=>{const start=q.selectionStart,end=q.selectionEnd;q.setRangeText(s,start,end,'end');q.focus()};bar.appendChild(b)});q.parentElement.appendChild(bar);const datalist=document.createElement('datalist');datalist.id='mathTags';document.body.appendChild(datalist);const tag=document.getElementById('fTag');if(tag)tag.setAttribute('list','mathTags');refreshTags()}
function refreshTags(){const dl=document.getElementById('mathTags');if(!dl)return;const tags=[...new Set(safe(KEYS.math,[]).map(q=>q.tag).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN'));dl.innerHTML=tags.map(t=>`<option value="${escapeHtml(t)}"></option>`).join('')}
function patchPaper(){if(typeof window.renderPaper!=='function'||window.renderPaper.__grade)return;const original=window.renderPaper;window.renderPaper=function(title,includeAnswers){original(title,includeAnswers);document.querySelectorAll('#paperContent .paper-question-list article').forEach((article,i)=>{const h=article.querySelector('h3'),question=(h?.textContent||'').replace(/^\d+\.\s*/,'');article.dataset.question=question;const grade=document.createElement('div');grade.className='paper-grade';grade.innerHTML=`<span>练习结果</span><label><input type="radio" name="grade-${i}" value="correct">做对</label><label><input type="radio" name="grade-${i}" value="wrong">做错</label><label><input type="radio" name="grade-${i}" value="skip" checked>暂不记录</label>`;article.appendChild(grade)});const actions=document.querySelector('.paper-actions');if(actions&&!actions.querySelector('.finish-paper')){const b=document.createElement('button');b.className='finish-paper';b.textContent='完成并保存结果';b.onclick=window.finishPaperReview;actions.appendChild(b)}};window.renderPaper.__grade=true}
window.finishPaperReview=function(){const all=safe(KEYS.math,[]);let correct=0,wrong=0;document.querySelectorAll('#paperContent .paper-question-list article').forEach((article,i)=>{const result=document.querySelector(`input[name="grade-${i}"]:checked`)?.value;if(result==='skip')return;const q=all.find(x=>x.subject==='数学'&&x.q===article.dataset.question);if(!q)return;q.lastReviewedAt=Date.now();q.edited=Date.now();if(result==='correct'){q.correctStreak=(q.correctStreak||0)+1;q.status=q.correctStreak>=2?'done':'review';correct++}else{q.correctStreak=0;q.status='wrong';wrong++}});if(!correct&&!wrong){notify('请至少标记一道题的练习结果');return}write(KEYS.math,all);logActivity('math-paper',`完成练习卷：做对 ${correct} 题，做错 ${wrong} 题`,correct+wrong);notify(`练习结果已保存：做对 ${correct} 题，做错 ${wrong} 题`);setTimeout(()=>location.reload(),700)};
function injectWordEdit(){document.querySelectorAll('.cards .card').forEach(card=>{const learn=card.querySelector('.actions .learn'),word=card.querySelector('.word')?.textContent?.trim();if(!learn||!word||card.querySelector('.edit-word'))return;const b=document.createElement('button');b.type='button';b.className='edit-word';b.textContent='编辑单词';b.onclick=()=>openWordEdit(word);learn.insertAdjacentElement('afterend',b)})}
function openWordEdit(word){const list=safe(KEYS.words,[]),item=list.find(w=>w.word===word);if(!item)return;let ov=document.getElementById('wordEditOverlay');if(!ov){ov=document.createElement('div');ov.id='wordEditOverlay';ov.className='overlay word-edit-overlay';ov.innerHTML='<section class="modal"><header><div><h2>编辑英语单词</h2><p>自动识别不准确时，可以在这里校正。</p></div><button type="button" onclick="document.getElementById(\'wordEditOverlay\').classList.remove(\'open\')">×</button></header><label>英文单词<input id="weWord"></label><label>中文释义<input id="weMeaning"></label><label>音标<input id="wePhonetic"></label><label>来源<input id="weSource"></label><label>音节拆分<input id="weSyllables" placeholder="用空格分隔，如 beau ti ful"></label><label>拼读提示<textarea id="weTip" rows="3"></textarea></label><label class="check-label"><input id="weIrregular" type="checkbox"> 标记为特殊拼写</label><button class="save" type="button" onclick="saveWordEdit()">保存修改</button></section>';document.body.appendChild(ov)}ov.dataset.word=word;document.getElementById('weWord').value=item.word;document.getElementById('weMeaning').value=item.meaning||'';document.getElementById('wePhonetic').value=item.phonetic||'';document.getElementById('weSource').value=item.source||'';document.getElementById('weSyllables').value=(item.syllables||[]).join(' ');document.getElementById('weTip').value=item.phonicsTip||'';document.getElementById('weIrregular').checked=!!item.isIrregular;ov.classList.add('open')}
window.saveWordEdit=function(){const ov=document.getElementById('wordEditOverlay'),old=ov?.dataset.word,list=safe(KEYS.words,[]),item=list.find(w=>w.word===old);if(!item)return;const next=(document.getElementById('weWord').value||'').trim().toLowerCase();if(!/^[a-z][a-z'-]*$/.test(next)){notify('请输入有效英文单词');return}if(list.some(w=>w!==item&&w.word===next)){notify('这个单词已经存在');return}item.word=next;item.meaning=document.getElementById('weMeaning').value.trim();item.phonetic=document.getElementById('wePhonetic').value.trim();item.source=document.getElementById('weSource').value.trim()||'手动添加';item.syllables=document.getElementById('weSyllables').value.trim().split(/\s+/).filter(Boolean);item.phonicsTip=document.getElementById('weTip').value.trim();item.isIrregular=document.getElementById('weIrregular').checked;write(KEYS.words,list);logActivity('english-edit',`编辑单词 ${next}`);location.reload()};
function rebuildRecent(){const box=document.getElementById('recentList');if(!box)return;let list=safe(KEYS.activity,[]).slice(-20);if(!list.length){const math=safe(KEYS.math,[]).map(q=>({type:'数学',text:'整理数学错题',at:q.edited||q.at||0})),history=safe(KEYS.history,[]).map(h=>({type:'英语',text:h.type==='spell'?'完成英语听写':'完成英语练习',at:h.at||0}));list=[...math,...history]}list=list.sort((a,b)=>b.at-a.at).slice(0,3);box.innerHTML=list.length?list.map(r=>`<div class="recent-row"><span class="recent-icon ${String(r.type).includes('english')||r.type==='英语'?'en':''}">${String(r.type).includes('english')||r.type==='英语'?'abc':'×'}</span><b>${String(r.type).includes('english')||r.type==='英语'?'英语':'数学'}</b><span>${escapeHtml(r.text)}</span><time>${new Date(r.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''):'<div class="recent-row">暂无学习记录</div>'}
function patchEnglishAccuracy(){const el=document.getElementById('recentAccuracy');if(!el)return;const spell=safe(KEYS.history,[]).filter(h=>h.type==='spell').slice(-20);el.textContent=spell.length?Math.round(spell.filter(h=>h.correct).length/spell.length*100)+'%':'—'}
function patchRender(){const fn=window.render;if(typeof fn!=='function'||fn.__reliable)return;const wrapped=function(...args){const r=fn.apply(this,args);setTimeout(()=>{injectWordEdit();patchEnglishAccuracy();refreshTags();rebuildRecent()},0);return r};wrapped.__reliable=true;window.render=wrapped}
function patchOpenProfile(){const fn=window.openProfileSettings;if(typeof fn!=='function'||fn.__backup)return;window.openProfileSettings=function(...a){const r=fn.apply(this,a);setTimeout(injectBackupManager,0);return r};window.openProfileSettings.__backup=true}
function keyboard(){document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;['profileOverlay','dataTransferOverlay','editOverlay','batchOverlay','paperBuilderOverlay','paperOverlay','lookupSheet','studyPage','wordEditOverlay'].forEach(id=>document.getElementById(id)?.classList.remove('open'));document.body.classList.remove('profile-modal-open','data-modal-open')})}
function staticSafetyCopy(){document.querySelectorAll('.safe-note span').forEach(el=>el.textContent='数据保存在当前设备，请定期导出完整备份。')}
function init(){migrateMath();repairEnglishDaily();overrideMathCard();patchPaper();patchRender();patchOpenProfile();formulaToolbar();keyboard();staticSafetyCopy();wrapDelete('removeQuestion',KEYS.math,'数学错题');wrapDelete('deleteSelected',KEYS.math,'所选数学错题');wrapDelete('removeWord',KEYS.words,'英语单词');wrapActivity('saveQuestion','math-edit','新增或编辑数学错题');wrapActivity('applyBatchStatus','math-review','批量更新数学掌握状态');wrapActivity('saveBatchEdit','math-edit','批量编辑数学错题');if(typeof window.recordResult==='function'){const f=window.recordResult;window.recordResult=function(w,type,correct,score){const r=f.apply(this,arguments);if(score&&type==='spell')logActivity('english-spell',`${correct?'听写正确':'听写错误'}：${w?.word||''}`);return r}}setTimeout(()=>{injectWordEdit();patchEnglishAccuracy();rebuildRecent()},80)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();